### ISSUE TITLE
Publish it on crates.io

### ISSUE THREAD

**Issue by XVilka** [marcelbuesing/doip#2]
It would be nice to have it easily reusable by anyone, especially since Rust recently got some recognition in automotive:
- https://foundation.rust-lang.org/news/announcing-the-safety-critical-rust-consortium/
- https://ferrous-systems.com/blog/new-safety-critical-rust-consortium/
- https://www.infineon.com/cms/en/about-infineon/press/market-news/2024/INFATV202404-089.html
- https://www.elektrobit.com/blog/rust-for-automotive-software/
- https://www.thoughtworks.com/en-in/insights/blog/programming-languages/rust-automotive-software

**Comment by marcelbuesing** [comment]
Done. It's published. Thanks for those links they look promising.
